name: Continuous Integration

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Dependencies
      run: sudo apt-get install libelf-dev libunwind-dev
    - name: Build
      run: make
    - name: Test
      run: make test
  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: make -f Makefile.win CC=gcc.exe
    - name: Echo R Version
      run: Rscript.exe --version
    - name: Test
      run: make -f Makefile.win RSCRIPT="Rscript.exe" SUDO="" test
